apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    karpenter.sh/provisioner-name: amd64
spec:
  containers:
  - name: example-container
    image: nginx
    resources:
      requests:
        cpu: 1
        memory: 1Gi
  nodeSelector:
    kubernetes.io/arch: amd64
    karpenter.sh/capacity-type: spot